name: spotix
description: Spotify client app

publish_to: "none"

version: 1.0.6

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: "2.10.5"

dependencies:
  cached_network_image: 3.2.0
  flutter:
    sdk: flutter
  get_it: 7.2.0
  package_info_plus: 1.4.2
  provider: 6.0.3
  quiver: 3.1.0
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  spotify_client:
    path: modules/spotify_client

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: "Maison Neue"
    fonts:
      - asset: assets/fonts/MaisonNeue-300.ttf
        weight: 300
      - asset: assets/fonts/MaisonNeue-400.ttf
        weight: 400
      - asset: assets/fonts/MaisonNeue-500.ttf
        weight: 500
      - asset: assets/fonts/MaisonNeue-600.ttf
        weight: 600
      - asset: assets/fonts/MaisonNeue-700.ttf
        weight: 700