name: spotify_client
description: Spotify Client Module
version: 0.0.2

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  equatable: 2.0.3
  flutter:
    sdk: flutter
  json_annotation: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter:
  plugin:
    platforms:
      android:
        package: app.iandis.spotify_client
        pluginClass: SpotifyClientPlugin
      ios:
        pluginClass: SpotifyClientPlugin
